IDS/Controllers/AuthController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using IDS.Models;
using IDS.Models.ViewModels;

using System.Net.NetworkInformation;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using DocumentFormat.OpenXml.Vml;
using Microsoft.CodeAnalysis;

namespace IDS.Controllers
{

   // [Authorize(Roles ="Admin")]
    public class AuthController : Controller
    {

        // service Layer of Identity
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;





        // SignInManager which creating cookie
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly AppDbContext _context;

        public AuthController(UserManager<ApplicationUser> userManager,  SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager , AppDbContext context)
        {
            this._userManager = userManager;
            this._signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
        }

        [AllowAnonymous]

        public IActionResult Index()
        {
            return RedirectToAction("LogIn");


        }

        public IActionResult Welcome()
        {
            return View();
        }





		[HttpGet]
        public IActionResult SignUp()
        {
          //  ViewBag.Colleges = _context.Colleges.Select(x => x.Name).ToList();  
            ViewBag.Roles = _roleManager.Roles.Select(r => r.Name).ToList();
            return View();
            
        }


        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpVm newUser)
        {
            ViewBag.Roles = _roleManager.Roles.Select(r => r.Name).ToList();
            // ViewBag.Colleges = _context.Colleges.Select(x => x.Name).ToList();


            //Debugging: Log ModelState errors if validation fails before creating the user
             List<string> errorsFromModelState = new List<string>();
             foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
            {
                errorsFromModelState.Add(error.ErrorMessage);
          
                //Console.WriteLine(error.ErrorMessage);
            }

            ViewBag.ErrrorsFromModelState = errorsFromModelState;

            if (ModelState.IsValid)
            {


                // Check if the user already exists
                var existingUser = await _userManager.FindByNameAsync(newUser.UserName);
                if (existingUser != null)
                {
                    ModelState.AddModelError("", "اسم المستخدم موجود بالفعل. الرجاء اختيار اسم آخر.");
                    return View(newUser);
                }

                // Check if the Email already exists
                var existingEmail = await _userManager.FindByEmailAsync(newUser.Email);
                if (existingEmail != null)
                {
                    ModelState.AddModelError("", "البريد الإلكتروني مسجل بالفعل. الرجاء استخدام بريد إلكتروني آخر.");
                    return View(newUser);
                }

                // Check if the PhoneNumber already exists
                var existingPhoneNumber = _userManager.Users.FirstOrDefault(u => u.PhoneNumber == newUser.PhoneNumber);
                if (existingPhoneNumber != null)
                {
                    ModelState.AddModelError("", "رقم الهاتف مستخدم من قبل شخص اخر");
                    return View(newUser);
                }

                ApplicationUser userModel = new ApplicationUser
                {
                    UserName = newUser.UserName,
                    FullName = newUser.FullName,
                    NationalId = newUser.NationalId,
                    Email = newUser.Email,
                    PhoneNumber = newUser.PhoneNumber,
                    Role = newUser.Role,
                    Address = newUser.Address
                };

                IdentityResult result = await _userManager.CreateAsync(userModel, newUser.Password);

                //string phoneNum = newUser.PhoneNumber;
                //string role = newUser.Role;

                //List<Claim> claims = new List<Claim>
                //    {
                //        new Claim("Phone", phoneNum),
                //        new Claim("Role", role)
                //    };

                //await _signInManager.SignInWithClaimsAsync(userModel, false, claims);

                  //Console.WriteLine("Badr " + "Mango" + User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier).Value);
                 // Console.WriteLine(User.Identity.IsAuthenticated);

                if (result.Succeeded)
                {

                    await _userManager.AddToRoleAsync(userModel, newUser.Role);
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    //foreach (var error in result.Errors)
                  //  {
                        ModelState.AddModelError("" , "حدث خطأ اثناء تسجيل البيانات, الرجاء مراجعة البيانات المدخله و المحاوله مرة اخري");
                   // }
                }
            }
            ModelState.AddModelError("" , "يبدو ان هناك بيانات غير صالحه, الرجاء مراجعة البيانات المدخله و المحاوله مرة اخري");
            return View(newUser); // Return the view with errors
        }



 

        [HttpGet]
        [AllowAnonymous]
        public IActionResult LogIn()
        {
            return View();
        }


        [AllowAnonymous]

        [HttpPost]
        public async Task<IActionResult> LogIn(LogInVm user)
        {
            //foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
            //{
            //    Console.WriteLine(error.ErrorMessage);
            //}

            if (ModelState.IsValid)
            {
                var userModel = await _userManager.FindByNameAsync(user.UserName);

                if (userModel != null)
                {
                    Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(userModel, user.Password, user.RememberMe, false);
         



                    if (result.Succeeded)
                    {
                        //Adding customized cookie when Doctor Sign in
                        
                            List<Claim> claims = new List<Claim>();
                            claims.Add(new Claim("Role", userModel.Role));
                    

                        if (userModel.Role == "Admin")
                        {
                            return RedirectToAction("Index", "Admin");

                        }
                        else if (userModel.Role == "Reception")
                        {
                            return RedirectToAction("Index", "Reception");
                        }
                        else if (userModel.Role == "Diagnosis-Nurse")
                        {
                            claims.Add(new Claim("DocName", userModel.FullName));
                            claims.Add(new Claim("DocId", userModel.Id));
                            await _signInManager.SignInWithClaimsAsync(userModel, new AuthenticationProperties
                            {
                                IsPersistent = false, // Ensures session-based authentication
                                AllowRefresh = true // Allows the session to be refreshed while the browser is open
                            }, claims);
                            return RedirectToAction("Index", "DiagnosisNurse");
                        }
                      
                        else if (userModel.Role == "Diagnosis-Doc")
                        {
                            return RedirectToAction("Index", "Diagnosis");
                        }
                        else if (userModel.Role == "CPresident")
                        {
                            var clinic = await _context.Clinics.Where(d => d.Supervisor == userModel.Id).FirstOrDefaultAsync();



                            claims.Add(new Claim("ClinicName", clinic.Name));
                            claims.Add(new Claim("ClinicId", clinic.Id.ToString()));
                         
                            claims.Add(new Claim("DocName", userModel.FullName));
                            claims.Add(new Claim("DocId", userModel.Id));


                            //  Ending the Cookie Making proccess
                            await _signInManager.SignInWithClaimsAsync(userModel, new AuthenticationProperties
                            {
                                IsPersistent = false, // Ensures session-based authentication
                                AllowRefresh = true // Allows the session to be refreshed while the browser is open
                            }, claims);

                            return RedirectToAction("Index", "ClinicPresident");
                        }

                        else if (userModel.Role == "EDoctor")
                        {

                            var doctor = await _context.Doctors.Where(d => d.Id == userModel.Id).FirstOrDefaultAsync();
                            var clinic = await _context.Clinics.Where(d => d.Id == doctor.ClinicId).FirstOrDefaultAsync();
                       

                            claims.Add(new Claim("ClinicName", clinic.Name));
                            claims.Add(new Claim("ClinicId", clinic.Id.ToString()));
                         
                            claims.Add(new Claim("DocName", userModel.FullName));
                            claims.Add(new Claim("DocId", userModel.Id));


                            //  Ending the Cookie Making proccess

IDS/Controllers/DoctorController.cs
using IDS.Models.ViewModels;
using IDS.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IDS.Controllers
{
    public class DoctorController : Controller
    {

        // service Layer of Identity
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;


        // SignInManager which creating cookie
        private readonly SignInManager<ApplicationUser> _signInManager;

        private readonly AppDbContext _context;

        public DoctorController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager, AppDbContext context)
        {
            this._userManager = userManager;
            this._signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public IActionResult SignUp()
        {
            ViewData["Clinics"] = (new SelectList(_context.Clinics, "Id", "Name"));
            ViewBag.Roles = _roleManager.Roles.Select(r => r.Name).ToList();
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpDoctorVm newUser)
        {
                    ViewData["Clinics"] = (new SelectList(_context.Clinics, "Id", "Name"));


            ViewBag.Roles = _roleManager.Roles.Select(r => r.Name).ToList();
            // ViewBag.Colleges = _context.Colleges.Select(x => x.Name).ToList();

            if (ModelState.IsValid)
            {
                // Check if the user already exists
                var existingUser = await _userManager.FindByNameAsync(newUser.UserName);
                if (existingUser != null)
                {
                    ModelState.AddModelError("", "اسم المستخدم موجود بالفعل. الرجاء اختيار اسم آخر.");
                    return View(newUser);
                }

                // Check if the Email already exists
                var existingEmail = await _userManager.FindByEmailAsync(newUser.Email);
                if (existingEmail != null)
                {
                    ModelState.AddModelError("", "البريد الإلكتروني مسجل بالفعل. الرجاء استخدام بريد إلكتروني آخر.");
                    return View(newUser);
                }


                // Check if the PhoneNumber already exists
                var existingPhoneNumber = _userManager.Users.FirstOrDefault(u => u.PhoneNumber == newUser.PhoneNumber);
                if (existingPhoneNumber != null)
                {
                    ModelState.AddModelError("", "رقم الهاتف مستخدم من قبل شخص اخر");
                    return View(newUser);
                }

                ApplicationUser userModel = new ApplicationUser
                {
                    UserName = newUser.UserName,
                    FullName = newUser.FullName,
                    NationalId = newUser.NationalId,
                    Email = newUser.Email,
                    PhoneNumber = newUser.PhoneNumber,
                    Role = newUser.Role,
                    Address = newUser.Address
                };

                Console.WriteLine($"UserName: [{newUser.UserName}]");

                IdentityResult result = await _userManager.CreateAsync(userModel, newUser.Password);

                if (!result.Succeeded)
                {
                    Console.WriteLine($"UserName: [{newUser.UserName}]");

                    foreach (var error in result.Errors)
                    {
                        Console.WriteLine($"Error Code: {error.Code}, Description: {error.Description}");
                    }
                }


                if (result.Succeeded)
                {

                    await _userManager.AddToRoleAsync(userModel, newUser.Role);

                    Doctor doctor = new Doctor
                    {
                        Id = userModel.Id,
                        ClinicId = newUser.ClinicId,
                        ActivePatientsUnderResposibility = 0,
                        Successfulcases = 0

                    };
                    _context.Add(doctor);
                    _context.SaveChanges();
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    //foreach (var error in result.Errors)
                    //  {
                    ModelState.AddModelError("", "حدث خطأ اثناء تسجيل البيانات, الرجاء مراجعة البيانات المدخله و المحاوله مرة اخري");
                    // }
                }
            }
            //Debugging: Log ModelState errors if validation fails before creating the user
            List<string> errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();

            ViewBag.errors = errors;
            ModelState.AddModelError("", "يبدو ان هناك بيانات غير صالحه, الرجاء مراجعة البيانات المدخله و المحاوله مرة اخري");
            return View(newUser); // Return the view with errors
        }



    }
}

IDS/Views/EDoctor/Index.cshtml
 @model IEnumerable<IDS.Models.Ticket>

@{
    ViewData["Title"] = "EDoctor page";
    Layout = null;
}


<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ًصفحة طبيب إمتياز</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">


    <link rel="stylesheet" href="~/css/CPresident.css">
    <link rel="stylesheet" href="~/css/Error.css">

</head>
<body>

    <!-- Success Container -->
    <div class="success-container" id="successContainer">
        @if (TempData["Success"] != null)
        {
            <div class="success-message">
                <i class="fas fa-check-circle"></i>
                <div class="success-content">
                    <div class="success-title">Done.</div>
                    <div class="success-details">@TempData["Success"]</div>
                    @*                     <div class="success-details">رقم التذكرة : @TempData["TicketId"]</div> *@

                </div>
                <button class="close-btn" onclick="closeMessage(this)">×</button>
            </div>
        }
    </div>

    <!-- Error Container -->
    <div class="error-container" id="errorContainer">
        @if (TempData["Error"] != null)
        {
            <div class="error-message">
                <i class="fas fa-exclamation-circle"></i>
                <div class="error-content">
                    <div class="error-title">Error</div>
                    <div class="error-details">@TempData["Error"]</div>
                </div>
                <button class="close-btn" onclick="closeMessage(this)">×</button>
            </div>
        }
    </div>

    <div class="container">
        <div class="header">
            <div class="header-content">
                <div class="logo">
                    <img src="~/images/logo.png" alt="شعار العيادة" class="logo-img">
                </div>
                <div class="header-text">
                    <h1>مرحبًا بكم</h1>
                    <h2>ملف الحالات الطبية</h2>
                    <p>د/@User.FindFirst("DocName")?.Value</p>
                </div>

                <div class="search-container">
                    <form action="#" method="get">
                        <input type="text" placeholder="ابحث باسم المريض أو رقم المذكرة..." class="search-input">
                        <button type="submit" class="search-button">
                            <i class="fas fa-search"></i>
                        </button>
                    </form>
                </div>
                <div class="Navs">

                    <a asp-action="" class="btn custom-hover" style="text-decoration: none;">
                        إحصائيات العيادة
                    </a>

                    <a asp-action="DoctorProfile" asp-controller="Doctor" class="btn custom-hover" style="text-decoration: none;">
                        حسابي
                    </a>


                    <a asp-action="SignOut" asp-controller="Auth" class="btn custom-hover" style="text-decoration: none;">
                        خروج
                    </a>


                </div>
            </div>
        </div>

        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>رقم التذكرة</th>
                        <th>تاريخ الزيارة</th>
                        <th>اسم المريض</th>
                        <th>رقم الهاتف</th>
                        <th>حالة التذكرة</th>
                        <th>تاريخ الزيارة القادمة</th>

                        <th class="actions-header">الإجراءات</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var entity in Model)
                    {
                        <tr>

                            <td>@entity.TicketId</td>
                            <td>@entity.AppointmentDate</td>
                            <td>@entity.Patient.Name</td>
                            <td>@entity.Patient.phoneNumber</td>
                            <td>
                                @(
                                    entity.LevelOfCompletness switch
                                    {
                                        "new" => "جديد",
                                        "follow-up" => "في مرحلة العلاج",
                                        "DidNotAttend" => "المريض لم يحضر الجلسة",
                                        "completed" => "تم العلاج بالكامل",
                                        _ => "جديد" // Default if null or unrecognized
                                    }
                                    )
                            </td>

                            <td>@(entity.NextDate.HasValue ? entity.NextDate.Value.ToString("yyyy-MM-dd") : "لم يحدد بعد")</td>
        

                            <td class="actions">

                                <a class="action-link view" asp-action="Edit" asp-Controller="@ViewBag.ControllerName" asp-route-id="@entity.TicketId"><i class="fas fa-eye"></i>فحص</a>
                                <a class="action-link view" asp-action="ShowPatientProfile" asp-Controller="@ViewBag.ControllerName" asp-route-id="@entity.Patient.PatientId"><i class="fas fa-eye"></i>عرض ملف المريض</a>

                                <button type="button" class="action-link view" style="border: none;" data-bs-toggle="modal" data-bs-target="#myModalEdit_@entity.TicketId">
                                    تحديد موعد زيارة
                                </button>

                                <div class="modal fade" id="myModalEdit_@entity.TicketId" tabindex="-1" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                 <h4>تحديد موعد زيارة قادمة</h4>
                                            </div>

                                            <div class="modal-body">
                                                <div class="PopUpDiv">
                                                    <form asp-controller="@ViewBag.controllerName" asp-action="ChangeNextDate" asp-route-id="@entity.TicketId" method="post">
                                                        <input type="hidden" name="id" Value="@entity.TicketId" />

                                                        <div class="mb-3">
                                                           

                                                            <label class="form-label" style="font-weight : bold;">إختر التاريخ</label>
                                                           <input type="date" class="form-control" id="date" name="Date" required style="width:70%; margin : auto;" />
                                                        </div>
                                                        <button type="submit" class="btn btn-primary btn-block" style="background : rgb(30, 100, 145); border:none;">حفظ</button>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button style=" margin-left : auto;" type="button" class="btn btn-dark" data-bs-dismiss="modal">رجوع</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <button type="button" class="action-link view" style="border: none;" data-bs-toggle="modal" data-bs-target="#myModalEdit2_@entity.TicketId">
                                      تعديل حالة التذكرة
                                </button>

                                <div class="modal fade" id="myModalEdit2_@entity.TicketId" tabindex="-1" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5>تعديل حالة التذكرة </h5>

                                            @*     <button type="button" class="btn-close" data-bs-dismiss="modal"></button> *@
                

                                            </div>

                                            <div class="modal-body">
                                                <div class="PopUpDiv">
                                                    <form asp-controller="@ViewBag.controllerName" asp-action="ChangeLevelOfCompletness" asp-route-id="@entity.TicketId" method="post">
                                                        <input type="hidden" name="id" Value="@entity.TicketId" />

                                                        <div class="mb-3">
                                                            <label class="form-label"><span style="font-weight:bold;">إسم المريض:</span> @entity.Patient.Name</label>                       
                                                            
                                                            <select name="LevelOfCompletionParameter" id="LevelOfCompletionParameter" class="status-select plain" style="border: 1px solid; border-radius:10px; width:70%;">
                                                                <option value="new">جديد</option>
                                                                <option value="follow-up">في مرحلة العلاج</option>
                                                                <option value="DidNotAttend">المريض لم يحضر الجلسة</option>
                                                                <option value="completed">تم العلاج بالكامل</option>
                                                            </select>
                                                        </div>
                                                        <button type="submit" class="btn btn-primary btn-block" style="background : rgb(30, 100, 145); border:none;">حفظ</button>
                                                    </form>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button style=" margin-left : auto;" type="button" class="btn btn-dark" data-bs-dismiss="modal">رجوع</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>

        <div class="footer">
            <p>جميع الحقوق محفوظة 2025 © فريق تطوير نظام "IDS"</p>
        </div>
    </div>

    <script src="~/js/CloseErrorMessage.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>